// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD-H_A7PMb0O8FjbXNpHAS074dl7R8rdRI",
      authDomain: "bgregistration-campaign.firebaseapp.com",
      projectId: "bgregistration-campaign",
      storageBucket: "bgregistration-campaign.appspot.com",
      messagingSenderId: "269311589693",
      appId: "1:269311589693:web:cf97eaa62feb637cfe1954",
      measurementId: "G-D0EWBCPWYJ");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyCIgYVKNfigOTGA-y4JKY6b4FrZjjiJ9gQ",
      authDomain: "bgregistration-campaign.firebaseapp.com",
      projectId: "bgregistration-campaign",
      storageBucket: "bgregistration-campaign.appspot.com",
      messagingSenderId: "269311589693",
      appId: "1:269311589693:android:2888c2e5286f73d0fe1954",
      measurementId: "G-D0EWBCPWYJ");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NfJWu5WK5ijKTFRj078WFFQHBCPHMro',
    appId: '1:174297607342:ios:66b07193d08c291622513f',
    messagingSenderId: '174297607342',
    projectId: 'bhavishyathukuguarantee-d3199',
    storageBucket: 'bhavishyathukuguarantee-d3199.appspot.com',
    androidClientId:
        '174297607342-ciuq9nkmut1lkqq650mql6kijhp5r4n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vregistration',
  );
}
